### PR TITLE
add maintainer guidelines

### PR DESCRIPTION
**Pull request by afeld**
:warning: **WIP** :warning: 

Don't know if makes sense to anyone besides me yet, but just wanted to show progress. Will comment again when it's more readable, but early feedback (esp. what should/shouldn't be in there) is more than welcome.

/cc @mbland @phirefly

### CODE REVIEW

**Comment by afeld** [comment]
Just had a chat w/ @msecret about merging his [Documentation Best Practices](https://docs.google.com/a/gsa.gov/document/d/1eMU8EA3pMNxww63CiHZLLDa8GC2pJxsJKOUCqf7Ed3k/edit#) into this document, and there is clearly a lot of work to be done on the page as is. A couple options with how to proceed:
- Merge this now with the [draft disclaimer](https://github.com/18F/open-source-program/commit/10ad3cbcb0075b0205fae69ae9499c71e14f5ce0), which means:
  - This one PR doesn't get too huge
  - We can do smaller PRs to `master` to modify it
  - It won't get a lot of :eyes: on it too early anyway, since the page is buried
- Leave this branch/PR open, which means:
  - We can do smaller PRs on top of it
  - We don't lose the ability to do inline commenting before merging the "MVP" version of the page
  - We don't clutter the site with half-baked pages

Preference?

**Comment by mbland** [comment]
Ping... Time to get this merged?

**Comment by afeld** [comment]
Some sections still need conversion from bullet points to paragraphs, but I'm ok w/ merging now and cleaning up w/ smaller PRs. :+1:

**Comment by mbland** [comment]
Gonna merge this; looking forward to getting more eyeballs on it during the Onboarding+Doc Sprint.

**Pull request merged**
